--SISTEMA
CREATE SCHEMA IF NOT EXISTS sistema AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS sistema_logs AUTHORIZATION postgres;

--USUARIOS
CREATE SCHEMA IF NOT EXISTS usuarios AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS usuarios_logs AUTHORIZATION postgres;


--ENTIDADE
CREATE SCHEMA IF NOT EXISTS entidade AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS entidade_logs AUTHORIZATION postgres;

--CADASTROS
CREATE SCHEMA IF NOT EXISTS cadastros AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS cadastros_logs AUTHORIZATION postgres;

--LISTAS
CREATE SCHEMA IF NOT EXISTS listas AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS listas_logs AUTHORIZATION postgres;

